import ClassModelToCodeConverterSerializableConfig
	from '@/erdiagram/converter/oop/code-converter/ClassModelToCodeConverterSerializableConfig';

export default interface TypeScriptClassModelToCodeConverterSerializableConfig extends ClassModelToCodeConverterSerializableConfig {

}
