import PlantUmlEntityRelationshipModelToDiagramCodeConverterConfig
	from '@/erdiagram/converter/diagram/plantuml/config/PlantUmlEntityRelationshipModelToDiagramCodeConverterConfig';

type PlantUmlEntityRelationshipModelToDiagramCodeConverterSerializableConfig = PlantUmlEntityRelationshipModelToDiagramCodeConverterConfig

export default PlantUmlEntityRelationshipModelToDiagramCodeConverterSerializableConfig;
