import DatabaseModelToCodeConverterSerializableConfig
	from '@/erdiagram/generator/database/code-converter/DatabaseModelToCodeConverterSerializableConfig';

export default interface SqlServerDatabaseModelToCodeConverterSerializableConfig extends DatabaseModelToCodeConverterSerializableConfig {

}
