export default interface EntityRelationshipModelParserConfig {
	allowUnknownEntities: boolean;
}

export type PartialEntityRelationshipModelParserConfig = Partial<EntityRelationshipModelParserConfig>;
export type EntityRelationshipModelParserSerializableConfig = EntityRelationshipModelParserConfig;
