import EntityRelationshipModelParserConfig from './EntityRelationshipModelParserConfig';
import entityRelationshipModelParserConfigManager, {EntityRelationshipModelParserConfigManager} from './EntityRelationshipModelParserConfigManager';

export {
	EntityRelationshipModelParserConfig,
	EntityRelationshipModelParserConfigManager,
	entityRelationshipModelParserConfigManager
};
