import ClassModelToCodeConverterSerializedConfig
	from '@/erdiagram/generator/oop/code-converter/ClassModelToCodeConverterSerializedConfig';

export default interface TypeScriptClassModelToCodeConverterSerializedConfig extends ClassModelToCodeConverterSerializedConfig {

}
