import ClassModelToCodeConverterSerializableConfig
	from '@/erdiagram/generator/oop/code-converter/ClassModelToCodeConverterSerializableConfig';

export default interface TypeScriptClassModelToCodeConverterSerializableConfig extends ClassModelToCodeConverterSerializableConfig {

}
