import DatabaseModelToCodeConverterSerializedConfig
	from '@/erdiagram/generator/database/code-converter/DatabaseModelToCodeConverterSerializedConfig';

export default interface OracleDatabaseModelToCodeConverterSerializedConfig extends DatabaseModelToCodeConverterSerializedConfig {

}
